name: Kickstart suggestion
description: Propose a new kickstart. No promises, but we might just build it!
title: "[Kickstart suggestion]: "
labels: 
  - kickstart_suggestion
  - unreviewed
assignees: 
  - keklundrh
body: 
  - type: markdown 
    attributes: 
      value: | 
        Please use this form to submit your idea for a future AI kickstart! 
  - type: textarea
    attributes: 
      label: Kickstart suggestion
      description: Please describe your vision for a kickstart in as much detail as possible.
      value: | 
        **Please describe your vision for a new kickstart** 
        What would you like to see? 

        **Is your suggestion related to a specific use case? Please describe.**
        A clear description of what the kickstart demonstrates and its value.

        **Describe the solution you'd like to see**
        A clear description of what you want to happen, or how you'd build it.

        **Additional context**
        Add any other context or screenshots about the suggestion here. 
    validations: 
      required: true 
